export const bouquets = [
  {
    id: "hr",
    name: "HR Paketi",
    icon: "🇭🇷",
    description: "Hrvatska televizija",
    color: "#3b82f6",
    glow: "rgba(59,130,246,0.35)",
    count: 42,
    channels: [
      { id: 1, name: "HRT 1", isLive: true, viewers: "12K", program: "Dnevnik", color: "#3b82f6" },
      { id: 2, name: "HRT 2", isLive: true, viewers: "5K", program: "Sport", color: "#3b82f6" },
      { id: 3, name: "HRT 3", isLive: true, viewers: "2K", program: "Kultura", color: "#3b82f6" },
      { id: 4, name: "Nova TV", isLive: true, viewers: "18K", program: "Vijesti Nova", color: "#ef4444" },
      { id: 5, name: "RTL Hrvatska", isLive: true, viewers: "15K", program: "RTL Direkt", color: "#f59e0b" },
      { id: 6, name: "Doma TV", isLive: false, viewers: "3K", program: "Film večeri", color: "#8b5cf6" },
      { id: 7, name: "Z1", isLive: true, viewers: "1K", program: "Grad Zagreb", color: "#10b981" },
    ],
  },
  {
    id: "sport",
    name: "Sport",
    icon: "⚽",
    description: "Sportski kanali",
    color: "#10b981",
    glow: "rgba(16,185,129,0.35)",
    count: 28,
    channels: [
      { id: 1, name: "Sport Klub 1", isLive: true, viewers: "22K", program: "Premijer liga", color: "#10b981" },
      { id: 2, name: "Sport Klub 2", isLive: true, viewers: "8K", program: "NBA košarka", color: "#10b981" },
      { id: 3, name: "Eurosport 1", isLive: true, viewers: "11K", program: "Tenis ATP", color: "#f59e0b" },
      { id: 4, name: "Eurosport 2", isLive: false, viewers: "4K", program: "Biciklizam", color: "#f59e0b" },
      { id: 5, name: "Arena Sport 1", isLive: true, viewers: "19K", program: "HNL live", color: "#ef4444" },
      { id: 6, name: "Arena Sport 2", isLive: true, viewers: "7K", program: "NBA All-Star", color: "#ef4444" },
      { id: 7, name: "DAZN", isLive: true, viewers: "33K", program: "Champions League", color: "#3b82f6" },
      { id: 8, name: "Sky Sport", isLive: false, viewers: "9K", program: "Football", color: "#6366f1" },
    ],
  },
  {
    id: "news",
    name: "Vijesti",
    icon: "📰",
    description: "Informativni kanali",
    color: "#f59e0b",
    glow: "rgba(245,158,11,0.35)",
    count: 18,
    channels: [
      { id: 1, name: "Al Jazeera", isLive: true, viewers: "5K", program: "Breaking News", color: "#f59e0b" },
      { id: 2, name: "CNN International", isLive: true, viewers: "8K", program: "World News", color: "#ef4444" },
      { id: 3, name: "BBC World", isLive: true, viewers: "12K", program: "Global Update", color: "#dc2626" },
      { id: 4, name: "N1 Info", isLive: true, viewers: "6K", program: "Vijesti N1", color: "#3b82f6" },
      { id: 5, name: "Euronews", isLive: true, viewers: "4K", program: "Europe Today", color: "#6366f1" },
      { id: 6, name: "DW News", isLive: false, viewers: "3K", program: "Deutschland", color: "#10b981" },
    ],
  },
  {
    id: "movies",
    name: "Filmovi",
    icon: "🎬",
    description: "Filmski kanali",
    color: "#8b5cf6",
    glow: "rgba(139,92,246,0.35)",
    count: 35,
    channels: [
      { id: 1, name: "HBO", isLive: true, viewers: "31K", program: "House of Dragon", color: "#dc2626" },
      { id: 2, name: "Cinemax", isLive: true, viewers: "14K", program: "Akcijski film", color: "#8b5cf6" },
      { id: 3, name: "AXN", isLive: true, viewers: "9K", program: "Thriller noir", color: "#6366f1" },
      { id: 4, name: "Fox Movies", isLive: false, viewers: "7K", program: "Comedy", color: "#f59e0b" },
      { id: 5, name: "FilmBox", isLive: true, viewers: "5K", program: "Classic Film", color: "#3b82f6" },
      { id: 6, name: "Pickbox NOW", isLive: true, viewers: "3K", program: "Domaći film", color: "#10b981" },
    ],
  },
  {
    id: "kids",
    name: "Dječji",
    icon: "🧒",
    description: "Za djecu",
    color: "#ec4899",
    glow: "rgba(236,72,153,0.35)",
    count: 15,
    channels: [
      { id: 1, name: "Cartoon Network", isLive: true, viewers: "19K", program: "Gumball", color: "#f59e0b" },
      { id: 2, name: "Nickelodeon", isLive: true, viewers: "22K", program: "SpongeBob", color: "#f97316" },
      { id: 3, name: "Disney Channel", isLive: true, viewers: "15K", program: "Disney Movie", color: "#3b82f6" },
      { id: 4, name: "HRT Kids", isLive: false, viewers: "4K", program: "Crtani", color: "#ec4899" },
      { id: 5, name: "Minimax", isLive: true, viewers: "8K", program: "Animacija", color: "#10b981" },
    ],
  },
  {
    id: "music",
    name: "Muzika",
    icon: "🎵",
    description: "Glazbeni kanali",
    color: "#a855f7",
    glow: "rgba(168,85,247,0.35)",
    count: 12,
    channels: [
      { id: 1, name: "MTV", isLive: true, viewers: "11K", program: "Music Charts", color: "#ec4899" },
      { id: 2, name: "VH1", isLive: false, viewers: "4K", program: "80s Hits", color: "#8b5cf6" },
      { id: 3, name: "CMC", isLive: true, viewers: "6K", program: "Domačica", color: "#3b82f6" },
      { id: 4, name: "Music Box", isLive: true, viewers: "3K", program: "Pop Hits", color: "#10b981" },
    ],
  },
  {
    id: "regional",
    name: "Regionalni",
    icon: "🌍",
    description: "Balkanski kanali",
    color: "#6366f1",
    glow: "rgba(99,102,241,0.35)",
    count: 55,
    channels: [
      { id: 1, name: "RTS 1", isLive: true, viewers: "8K", program: "Vijesti RTS", color: "#ef4444" },
      { id: 2, name: "Pink TV", isLive: true, viewers: "21K", program: "Zadruga LIVE", color: "#ec4899" },
      { id: 3, name: "Prva TV", isLive: false, viewers: "7K", program: "Serija", color: "#f59e0b" },
      { id: 4, name: "FTV BIH", isLive: true, viewers: "5K", program: "Dnevnik FTV", color: "#3b82f6" },
      { id: 5, name: "OBN", isLive: true, viewers: "4K", program: "OBN Info", color: "#10b981" },
      { id: 6, name: "Kanal 5 MK", isLive: false, viewers: "2K", program: "Film", color: "#8b5cf6" },
    ],
  },
  {
    id: "international",
    name: "Internacionalni",
    icon: "🌐",
    description: "Svjetski kanali",
    color: "#0891b2",
    glow: "rgba(8,145,178,0.35)",
    count: 48,
    channels: [
      { id: 1, name: "Sky One", isLive: true, viewers: "14K", program: "Premier Show", color: "#3b82f6" },
      { id: 2, name: "Fox", isLive: true, viewers: "9K", program: "Fox News", color: "#ef4444" },
      { id: 3, name: "Discovery", isLive: true, viewers: "6K", program: "Nature Doc", color: "#10b981" },
      { id: 4, name: "National Geographic", isLive: false, viewers: "5K", program: "Space", color: "#f59e0b" },
      { id: 5, name: "History", isLive: true, viewers: "4K", program: "WW2 Doc", color: "#8b5cf6" },
    ],
  },
];